laterpay/supertab-browser

__snapshots__/Supertab.test.ts.snap
src/index.ts

Ref: https://laterpay.atlassian.net/browse/CL-1568
- This PR adds the property `connectedSubscriptionOffering` to the offerings returned by the method `getOfferings`.
- This is required in order to render the TimePass-Subscription relationships in the basic PayGate experience just like in the COW.

feat: Expose connected subscription offerings

---

src/index.ts

Remove the temporary property `connectedSubscriptionOfferingId` from method `getOfferings` because it leakes into the return type of the method.

fix: Refactor connected subscription logic to fix TypeScript issue

---

tsup.stg.config.ts

https://laterpay.atlassian.net/browse/SET-2361
Now that Hydra on STG is configured with the supertab.co domain
(see https://github.com/laterpay/terraform-lpeu-stg-tapper-auth/pull/12)
we can switch back to the original auth endpoint on Hydra
instead of the hacky SSO auth endpoint.
See more at https://github.com/laterpay/tapper-sso/pull/1368.
https://laterpay.atlassian.net/wiki/spaces/~835572784/pages/3194945538/Getting+rid+of+laterpay+from+the+Supertab+system#COW
Switch from `https://signon.stg.supertab.co/oauth2/auth`
to `https://auth.stg.supertab.co/oauth2/auth`

Switch back to Hydra auth endpoint STG

---

.env.local
.env.test
tsup.sbx.config.ts

https://laterpay.atlassian.net/browse/SET-2361
Now that Hydra on SBX is configured with the supertab.co domain
(see https://github.com/laterpay/terraform-lpeu-sbx-tapper-auth/pull/32)
we can switch back to the original auth endpoint on Hydra
instead of the hacky SSO auth endpoint.
See more at https://github.com/laterpay/tapper-sso/pull/1368.
https://laterpay.atlassian.net/wiki/spaces/~835572784/pages/3194945538/Getting+rid+of+laterpay+from+the+Supertab+system#COW
Switch from `https://signon.sbx.supertab.co/oauth2/auth`
to `https://auth.sbx.supertab.co/oauth2/auth`

Switch back to Hydra auth endpoint on SBX

---

.env.production
tsup.prod.config.ts

https://laterpay.atlassian.net/browse/SET-2361
https://laterpay.atlassian.net/wiki/spaces/~835572784/pages/3194945538/Getting+rid+of+laterpay+from+the+Supertab+system
One of the final steps in the process of cleaning up old `laterpay` name.

Switch to supertab.co domain on PROD

---

.env.production
tsup.prod.config.ts

https://laterpay.atlassian.net/browse/SET-2361
Now that Hydra on PROD is configured with the supertab.co domain
(see https://github.com/laterpay/terraform-lpeu-prod-tapper-auth/pull/20)
we can switch back to the original auth endpoint on Hydra
instead of the hacky SSO auth endpoint.
See more at https://github.com/laterpay/tapper-sso/pull/1368.
https://laterpay.atlassian.net/wiki/spaces/~835572784/pages/3194945538/Getting+rid+of+laterpay+from+the+Supertab+system#COW
Switch from `https://signon.supertab.co/oauth2/auth`
to `https://auth.supertab.co/oauth2/auth`

Switch back to Hydra auth endpoint on PROD

---

Supertab.test.ts
__snapshots__/Supertab.test.ts.snap
src/index.ts
src/types.ts
tsup.stg.config.ts

BREAKING CHANGE: Change currency type from `string` (isoCode) to `object` (isoCode, baseUnit)
Offerings, tabs and tab purchases now contain more currency details in the form of an object. Before, they contained just the currency iso code string.
```typescript
type PublicCurrencyDetails = Pick<Currency, "isoCode" | "baseUnit">;
// Example
const currency: PublicCurrencyDetails = {
isoCode: "USD",
baseUnit: 100,
};
```
We're implementing Google's Monetization Provider API for experiences.js and we need to know the currency's base unit for the response data.
- **fix: Correct typo in STG token URL**
- **Add missing data to mock user**
- **Include currency isoCode and baseUnit in offerings**
- **Include currency iso code and base unit in tabs**
- **Fix inconsitent currency handling in test mock …

feature: Include more currency details in offerings and tabs

---

Supertab.test.ts
src/index.ts
src/window.ts

This PR adds `getCurrencyDetails` method to the browser SDK. The method is exposing currency properties, allowing integrations to access currency specific properties like `firstTabLimit` and `tabLimit`. This partially unblocks rendering the contextual help text "You only pay when your tab reaches X" where X is either regular tab limit or first tab limit.
* `isoCode`: `string` – passing valid currency ISO code will return currency details in a requested currency. Defaults to the suggested currency from the experiences config.
```typescript
type GetCurrencyResponse = {
isoCode: string;
name: string;
symbol: string;
baseUnit: number;
firstTabLimit: {
amount: number;
text: string;
},
tabLimit: {
amount: number;
text: string;
}
}
```
```js
{
isoCode: "USD",
name: "US Dollar",
symbol: "$", …
```

feat: add `getCurrencyDetails` method

---

Supertab.test.ts
src/index.ts

This PR makes `isoCode` function argument in `getCurrencyDetails` optional. It was intended to be optional originally but in #147 we mistakenly made it required.

fix: make `isoCode` in `getCurrencyDetails` optional

---

Supertab.test.ts
src/index.ts
src/mocks/server.ts

This PR adds optional `contentKey` argument to `checkAccess` function. It allows checking access by a specific content key, rather than the first content key found in the client config.
To keep the backwards compatibility, the function still looks up the first content key in the client config in case `contentKey` is not specified. This ensures the existing integrations won't break. This is because we will be moving away from client config entirely soon so the plan is to introduce one major version with all related breaking changes.

feat: make `checkAccess` accept optional `contentKey` to check access for specific key

---

src/index.ts

This PR fixes preferred currency price logic in `getOfferings` when setting `price` value. It's bringing it in line with how we handle it in `getExperience`.
The previous implementation led into issues for users with existing tabs in different currency. The `price` object was set to the currency of an existing tab, but the amount was set to the preferred currency that `getOfferings` accepts as an argument.
A user with tab in EUR visited a site calling `getOfferings` with `INR` as preferred currency. The price of the offering was set to 600 INR and 6 EUR. User was presented with `€600` instead of `₹600`.

fix: return correct price for preferred currency

---

Supertab.test.ts
__snapshots__/Supertab.test.ts.snap
src/index.ts

This PR formats properties including prices of `mainOffering` and `upsellOffering` offering pairs in `upsells` object returned in the `getExperience`. This unblocks clients, allowing them to use the formatted prices returned by the `supertab-browser` in their integrations rather than having to format prices of upsell offerings on their end.

fix: format upsell offerings in getExperience

---

src/index.ts
src/types.ts

This PR adds `UiConfig` type and uses it for `uiConfig` property returned by `getExperience` method.
Ref: https://laterpay.atlassian.net/browse/CL-1813

feat: UiConfig type

---

src/index.ts

[Jira ticket](https://laterpay.atlassian.net/browse/CL-1845)
This PR is a temporary fix for checking if `subscription_id` is `None`:
More context [here](https://supertab.slack.com/archives/C07TV0SUGSC/p1738329991624189)
Next steps: 
- Update `supertab-browser` version in `supertab-js` once this is merged

fix: check against subscription id that can be a None string

---

src/index.ts

Ref: https://laterpay.atlassian.net/browse/CL-1869
- This fixes a regression from the COW to `supertab-js` (which uses `supertab-browser` for OAuth)
- Default to the `redirectUri` from the experience config API response instead of using `window.location.origin`
- Our OAuth setup can only support subdomains (like www) if we use the `redirectUri` from the experience config, not the current page's origin
- See the related Slack discussion for more details: https://supertab.slack.com/archives/C044ZLL80E9/p1739370146174699

fix(CL-1869): default to redirect URI from experience config

---

src/index.ts

Ref: https://laterpay.atlassian.net/browse/CL-1869
- The first attempt to fix the issue (#175) resulted in a duplication of the base part of the redirect URI
- The `redirectUri` from the experiences config API response already contains the **full URL**

fix(CL-1869): Use full redirect URI from experiences config

---

src/index.ts

[CL-1870](https://laterpay.atlassian.net/browse/CL-1870)
Changes: 
- Allowed to pass metadata prop to the `purchase` function
[CL-1870]: https://laterpay.atlassian.net/browse/CL-1870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: allow to pass metadata to the purchase function

---

src/index.ts

Just a draft attempt to fix checkAccess with `validContentKey`
then actor logic in supertab-js handles it gracefully 
```
const { access } = await supertabClient.checkAccess();
if (access?.validTo !== undefined) {
// Only proceeds if there's a valid access 
return sendBack({
type: "priorEntitlement",
priorEntitlement: access,
});
}
// Default to no entitlement - this handles null access 
return sendBack({ type: "noEntitlement" });
```

fix: check valid key

---

src/window.ts

[CL-1918](https://laterpay.atlassian.net/browse/CL-1918)
**Bug:** The bug was caused by a SecurityError thrown when attempting to access openedWindow.location.href after the child window navigated to a cross-origin URL.
**Fix:** The fix wraps the access in a try/catch to safely detect when the URL is no longer accessible due to same-origin policy restrictions. 
- I was able to reproduce the bug for other browsers (not just for Safari)
- the fix was tested via `yarn link`
https://github.com/user-attachments/assets/2b8fd126-5d69-4c18-aa57-7909a6c40206
https://github.com/user-attachments/assets/f6c13ab2-79a1-4608-81d2-e18027fc14d6
[CL-1918]: https://laterpay.atlassian.net/browse/CL-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: authorize cross-origin window

---

src/types.ts

This PR adds `highlightedUpsellOfferingIds` to `UiConfig` type for both `mainScreen` and `moreOptionsScreen`. This is to support the development of a new feature to allow highlighting upsells in the business portal.
_Note: To fully deprecate this package and stop relying on it, we should consider moving these types somewhere else. Currently, Business Portal and Design System use them. To be addressed separately, will add to agenda for next eng sync._

feat: add highlighted upsell offering ids to `UiConfig`
